# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0007_auto_20171227_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='isCartoon',
        ),
        migrations.AddField(
            model_name='movie',
            name='Type',
            field=models.CharField(choices=[(b'0', b'Movie'), (b'1', b'Cartoon')], default=b'Human', max_length=100),
        ),
    ]
