# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0008_auto_20171228_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='Text',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='Race',
            field=models.CharField(choices=[(b'Whill', b'Whill'), (b'Human', b'Human'), (b'Kaleesh', b'Kaleesh'), (b'Cyborg', b'Cyborg'), (b'Zabrak', b'Zabrak'), (b'Korun', b'Korun'), (b'Droid', b'Droid'), (b'Clone', b'Clone'), (b'Kel Dor', b'Kel Dor'), (b'Wookiee', b'Wookiee'), (b'Hutt', b'Hutt')], default=b'Human', max_length=100),
        ),
    ]
